version: "3.9"

services:
  backend:
    build: ./server
    container_name: imagify-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    environment:
      - PORT=4000
      - NODE_ENV=production

  frontend:
    build: ./client
    container_name: imagify-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=https://imagify-backend-oe0c.onrender.com/
      - VITE_RAZORPAY_KEY_ID=rzp_test_RRRdlwqv8Tdmji
    depends_on:
      - backend
